// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Option struct {
	ID       int64
	Option   string
	Correct  bool
	TriviaID uuid.UUID
}

type Quiz struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	QuizType     string
	QuizCategory string
	UserID       uuid.UUID
	ScoreID      uuid.NullUUID
}

type QuizzesTrivia struct {
	ID       uuid.UUID
	QuizID   uuid.UUID
	TriviaID uuid.UUID
}

type Score struct {
	ID                uuid.UUID
	CompletionTime    int64
	HardQuizzesDone   int32
	MediumQuizzesDone int32
	EasyQuizzesDone   int32
	TotalScore        int32
	UserID            uuid.UUID
}

type Trivia struct {
	ID         uuid.UUID
	Type       string
	Category   string
	Difficulty string
	Question   string
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Email     string
}
