// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Quiz struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	QuizType     string
	QuizCategory string
	UserID       uuid.UUID
}

type Score struct {
	ID                uuid.UUID
	CompletionTime    int64
	HardQuizzesDone   int32
	MediumQuizzesDone int32
	EasyQuizzesDone   int32
	TotalScore        int32
	UserID            uuid.UUID
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
}
