// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: quizzes.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO quizzes (
	id,
	created_at,
	quiz_type,
	quiz_category,
	user_id
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, quiz_type, quiz_category, user_id, score_id
`

type CreateQuizParams struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	QuizType     string
	QuizCategory string
	UserID       uuid.UUID
}

func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error) {
	row := q.db.QueryRowContext(ctx, createQuiz,
		arg.ID,
		arg.CreatedAt,
		arg.QuizType,
		arg.QuizCategory,
		arg.UserID,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.QuizType,
		&i.QuizCategory,
		&i.UserID,
		&i.ScoreID,
	)
	return i, err
}

const getQuizByUserID = `-- name: GetQuizByUserID :many
SELECT id, created_at, quiz_type, quiz_category, user_id, score_id FROM quizzes
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetQuizByUserID(ctx context.Context, userID uuid.UUID) ([]Quiz, error) {
	rows, err := q.db.QueryContext(ctx, getQuizByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quiz
	for rows.Next() {
		var i Quiz
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.QuizType,
			&i.QuizCategory,
			&i.UserID,
			&i.ScoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScoreID = `-- name: UpdateScoreID :one
UPDATE quizzes
SET score_id = $1
WHERE id = $2
RETURNING id, created_at, quiz_type, quiz_category, user_id, score_id
`

type UpdateScoreIDParams struct {
	ScoreID uuid.NullUUID
	ID      uuid.UUID
}

func (q *Queries) UpdateScoreID(ctx context.Context, arg UpdateScoreIDParams) (Quiz, error) {
	row := q.db.QueryRowContext(ctx, updateScoreID, arg.ScoreID, arg.ID)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.QuizType,
		&i.QuizCategory,
		&i.UserID,
		&i.ScoreID,
	)
	return i, err
}
