// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: quizzes_trivias.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createQuizTrivia = `-- name: CreateQuizTrivia :one
INSERT INTO quizzes_trivias (
	id,
	quiz_id,
	trivia_id
)
VALUES ($1, $2, $3)
RETURNING id, quiz_id, trivia_id
`

type CreateQuizTriviaParams struct {
	ID       uuid.UUID
	QuizID   uuid.UUID
	TriviaID uuid.UUID
}

func (q *Queries) CreateQuizTrivia(ctx context.Context, arg CreateQuizTriviaParams) (QuizzesTrivia, error) {
	row := q.db.QueryRowContext(ctx, createQuizTrivia, arg.ID, arg.QuizID, arg.TriviaID)
	var i QuizzesTrivia
	err := row.Scan(&i.ID, &i.QuizID, &i.TriviaID)
	return i, err
}

const getQuizTriviaByID = `-- name: GetQuizTriviaByID :one
SELECT id, quiz_id, trivia_id FROM quizzes_trivias
WHERE id = $1
`

func (q *Queries) GetQuizTriviaByID(ctx context.Context, id uuid.UUID) (QuizzesTrivia, error) {
	row := q.db.QueryRowContext(ctx, getQuizTriviaByID, id)
	var i QuizzesTrivia
	err := row.Scan(&i.ID, &i.QuizID, &i.TriviaID)
	return i, err
}

const getQuizzesByTriviaID = `-- name: GetQuizzesByTriviaID :many
SELECT quizzes_trivias.id, quizzes.id, quizzes.created_at, quizzes.quiz_type, quizzes.quiz_category, quizzes.user_id, quizzes.score_id FROM quizzes_trivias
JOIN quizzes ON quizzes_trivias.quiz_id = quizzes.id
WHERE quizzes_trivias.trivia_id = $1
`

type GetQuizzesByTriviaIDRow struct {
	ID           uuid.UUID
	ID_2         uuid.UUID
	CreatedAt    time.Time
	QuizType     string
	QuizCategory string
	UserID       uuid.UUID
	ScoreID      uuid.NullUUID
}

func (q *Queries) GetQuizzesByTriviaID(ctx context.Context, triviaID uuid.UUID) ([]GetQuizzesByTriviaIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getQuizzesByTriviaID, triviaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuizzesByTriviaIDRow
	for rows.Next() {
		var i GetQuizzesByTriviaIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ID_2,
			&i.CreatedAt,
			&i.QuizType,
			&i.QuizCategory,
			&i.UserID,
			&i.ScoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTriviasByQuizID = `-- name: GetTriviasByQuizID :many
SELECT quizzes_trivias.id, trivias.id, trivias.type, trivias.category, trivias.difficulty, trivias.question FROM quizzes_trivias
JOIN trivias ON quizzes_trivias.trivia_id = trivias.id
WHERE quizzes_trivias.quiz_id = $1
`

type GetTriviasByQuizIDRow struct {
	ID         uuid.UUID
	ID_2       uuid.UUID
	Type       string
	Category   string
	Difficulty string
	Question   string
}

func (q *Queries) GetTriviasByQuizID(ctx context.Context, quizID uuid.UUID) ([]GetTriviasByQuizIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getTriviasByQuizID, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTriviasByQuizIDRow
	for rows.Next() {
		var i GetTriviasByQuizIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ID_2,
			&i.Type,
			&i.Category,
			&i.Difficulty,
			&i.Question,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
